#!/usr/bin/env python
#-*- coding: utf-8 -*-
menu = {
    '北京': {
        '海淀': {
            '五道口': {
                'soho': {},
                '网易': {},
                'google': {}
            },
            '中关村': {
                '爱奇艺': {},
                '汽车之家': {},
                'youku': {},
            },
            '上地': {
                '百度': {},
            },
        },
        '昌平': {
            '沙河': {
                '老男孩': {},
                '北航': {},
            },
            '天通苑': {},
            '回龙观': {},
        },
        '朝阳': {},
        '东城': {},
    },
    '上海': {
        '闵行': {
            "人民广场": {
                '炸鸡店': {}
            }
        },
        '闸北': {
            '火车站': {
                '携程': {}
            }
        },
        '浦东': {},
    },
    '山东': {},
}
menu_1 = menu
back = []
while True:
    for k in menu_1:
        print(k)
    next_1 = input("< ").strip()
    if not next_1:
        continue
    if next_1 in menu_1:
        # 把每次的字典值记录在列表中，然后通过删除最后一个列表值，可以返回上级菜单
        back.append(menu_1)
        # 使每级菜单通过for循环执行，例如第一次menu_1 = menu_1["北京"],第二次 menu_1 = menu_1["北京"]["海淀"]以此类推
        menu_1 = menu_1[next_1]
    elif next_1 == "q":
        break
    elif next_1 == "b":
        # 删除back记录的列表值的最后一位，例如当前在五道口，现在列表中记录两个值0是北京{}1是海淀{},通pop删除海淀值并返回删除的
        # 值，再通过for k in menu_1打印出上级菜单的keys
        menu_1 = back.pop()
